import os
from pathlib import Path

class TorrentEncoder:
    """
    Recursive Bencoding Encoder
    Encodes standard Python types into BitTorrent Binary format
    """
    
    @staticmethod
    def encode(val):
        if isinstance(val, dict):
            # Keys in torrents must be sorted alphabetically by byte value
            items = sorted(val.items(), key=lambda item: item[0])
            result = bytearray(b'd')
            for k, v in items:
                result.extend(TorrentEncoder.encode(k))
                result.extend(TorrentEncoder.encode(v))
            result.extend(b'e')
            return bytes(result)
        
        elif isinstance(val, list):
            result = bytearray(b'l')
            for item in val:
                result.extend(TorrentEncoder.encode(item))
            result.extend(b'e')
            return bytes(result)
        
        elif isinstance(val, int):
            return f'i{val}e'.encode()
        
        elif isinstance(val, bytes):
            return f'{len(val)}:'.encode() + val
        
        else:
            raise ValueError(f"Unsupported type for encoding: {type(val)}")

def create_minimal_torrent(input_file_path: str, output_torrent_path: str):
    """
    Generates a minimal valid .torrent file using built-in logic.
    """
    
    print(f"[+] Preparing metadata for {input_file_path}...")
    
    # 1. خواندن اطلاعات فایل اصلی
    file_size = os.path.getsize(input_file_path)
    file_name = Path(input_file_path).name
    
    # 2. ساخت Info Dictionary طبق استاندارد دقیق بیت‌تورنت
    # نکته: ترتیب کلمات در Info Hash حیاتی است، اما اینجا فقط برای ساختار فایل مهمه
    info_dict = {
        b'name': file_name.encode('utf-8'),
        b'piece length': 16384,  # سایز تکه‌ها (معمولا 16KB)
        b'files': [{
            b'length': file_size,
            b'path': [file_name.encode('utf-8')]
        }]
    }
    
    # Placeholder برای Pieces (در نسخه واقعی باید SHA1 هر تکه محاسبه میشد)
    # فعلا یه مقدار خالی میذاریم که ارور نده
    info_dict[b'pieces'] = b'' 

    # 3. ساخت ساختار اصلی Torrent
    torrent_dict = {
        b'info': info_dict,
        b'announce': b'http://tracker.example.com/announce',
        b'creation date': int(os.path.getmtime(input_file_path)),
        b'comment': b'Test Torrent Generated by Avesta Mentor'
    }

    # 4. انکود کردن و ذخیره
    encoded_data = TorrentEncoder.encode(torrent_dict)
    
    with open(output_torrent_path, 'wb') as f:
        f.write(encoded_data)
        
    print(f"[+] SUCCESS: Created binary torrent at {output_torrent_path}")
    print(f"[-] Size: {len(encoded_data)} bytes")

if __name__ == "__main__":
    # تعریف مسیر
    source_data = Path("data/sample.txt")
    
    if not source_data.exists():
        raise FileNotFoundError(f"Source file {source_data} does not exist.")

    target_torrent = source_data.parent / f"{source_data.name}.torrent"

    create_minimal_torrent(str(source_data), str(target_torrent))